"""
Django settings for DRF Template project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import logging
from environment.variables import EnvironmentVariable
from decouple import config
from corsheaders.defaults import default_headers

# List of available environments
ENVIRONMENT_MAIN = "MAIN"


# Defining Environment
def set_environment(environment):
    if environment == ENVIRONMENT_MAIN:
        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "environment.main")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!-6)6596_)!ak74af#ei5m#nhu_cq*pvqb)armoer$2)86y6#v'

# SECURITY WARNING: don't run with debug turned on in production!

if EnvironmentVariable.DEBUG == "True":
    DEBUG = True
else:
    DEBUG = False

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom Packages
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # Apps
    'user',
    'tasks',
    'common',

    # extra
    'django_filters',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated"
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'EXCEPTION_HANDLER': 'exceptions.app_exception_handler',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

ROOT_URLCONF = 'common.urls'

CORS_ALLOW_HEADERS = list(default_headers) + [
    'Content-Disposition',
    'X-Api-Key'
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "https://api-nft.macd.gg"
]
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = True
CORS_ALLOWED_ORIGINS = ALLOWED_ORIGINS
CSRF_TRUSTED_ORIGINS = ALLOWED_ORIGINS
CORS_ORIGIN_WHITELIST = ALLOWED_ORIGINS

BACKEND_SOURCES = (
    "'self'",

    # For Swagger
    'unpkg.com',
    "'unsafe-inline'"
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'staticfiles': 'django.templatetags.static',
            },
        },
    },
]

WSGI_APPLICATION = 'common.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# Extra places for collectstatic to find static files.

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static_files'),)
# MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configurations
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)

AWS_ACCESS_KEY_ID = EnvironmentVariable.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = EnvironmentVariable.AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = EnvironmentVariable.AWS_STORAGE_BUCKET_NAME
AWS_DEFAULT_ACL = None
AWS_S3_ENDPOINT_URL = EnvironmentVariable.AWS_S3_ENDPOINT_URL
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_LOCATION = EnvironmentVariable.AWS_MEDIA_FOLDER
AWS_QUERYSTRING_AUTH = False
# s3 public media settings
MEDIA_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)
DEFAULT_FILE_STORAGE = 'environment.storage.PublicMediaStorage'
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE