# Generated by Django 5.1.4 on 2026-03-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('FOLLOW_TWITTER', 'Follow official twitter account'), ('JOIN_GARAGE_TELEGRAM', 'Join the Garage telegram'), ('LIKE_TWEET', 'Like promotional tweets'), ('RETWEET_ANNOUNCEMENT', 'Retweet announcements'), ('WRITE_THREAD', 'Write an informational thread'), ('FOLLOW_INSTAGRAM', 'Follow Instagram account'), ('JOIN_DISCORD', 'Join Discord server'), ('SHARE_POST', 'Share social media post'), ('DAILY_LOGIN_REWARD', 'Daily login reward')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Social Task',
                'verbose_name_plural': 'Social Tasks',
                'db_table': 'social_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSocialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Social Task',
                'verbose_name_plural': 'User Social Tasks',
                'db_table': 'user_social_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
