# Generated by Django 5.2.12 on 2026-03-09 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('user', '0005_remove_user_active_tab_id_remove_user_email_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socialtask',
            index=models.Index(fields=['active', '-created_at'], name='social_task_active_96becf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialtask',
            index=models.Index(fields=['user', 'task'], name='user_social_user_id_5f9e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialtask',
            index=models.Index(fields=['user', 'verified'], name='user_social_user_id_483035_idx'),
        ),
        migrations.AddIndex(
            model_name='usersocialtask',
            index=models.Index(fields=['user', '-created_at'], name='user_social_user_id_14d2ec_idx'),
        ),
    ]
