# Generated by Django 5.1.4 on 2026-03-05 07:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import environment.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FLOWER', 'Flower'), ('BANANA', 'Banana')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('points_per_item', models.IntegerField(help_text='Points awarded when this item is consumed', validators=[django.core.validators.MinValueValidator(1)])),
                ('emoji', models.CharField(help_text='Emoji representation of the food item', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'db_table': 'food_item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, storage=environment.storage.PublicMediaStorage(), upload_to='')),
                ('wallet_address', models.CharField(blank=True, max_length=90, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('referral_rewards_claimed', models.BooleanField(default=False, help_text='Whether referral rewards have been claimed')),
                ('total_points', models.IntegerField(default=0)),
                ('last_points_update', models.DateTimeField(auto_now=True)),
                ('active_tab_id', models.CharField(blank=True, help_text='Currently active tab ID', max_length=100, null=True)),
                ('last_active', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp from active tab', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points_earned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_consumptions', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.fooditem')),
            ],
            options={
                'verbose_name': 'Food Consumption',
                'verbose_name_plural': 'Food Consumptions',
                'db_table': 'food_consumption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LootBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=environment.storage.PublicMediaStorage(), upload_to='')),
                ('cost_quantity', models.IntegerField(help_text='Number of food items required to purchase', validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_limit_per_user', models.IntegerField(blank=True, help_text='Max purchases per user (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lootboxes_for_sale', to='user.fooditem')),
            ],
            options={
                'verbose_name': 'Loot Box',
                'verbose_name_plural': 'Loot Boxes',
                'db_table': 'loot_box',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LootBoxReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_min', models.IntegerField(help_text='Minimum quantity that can be won', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_max', models.IntegerField(help_text='Maximum quantity that can be won', validators=[django.core.validators.MinValueValidator(1)])),
                ('drop_rate', models.FloatField(help_text='Probability weight (higher = more common)', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='user.lootbox')),
                ('reward_food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lootbox_rewards', to='user.fooditem')),
            ],
            options={
                'verbose_name': 'Loot Box Reward',
                'verbose_name_plural': 'Loot Box Rewards',
                'db_table': 'loot_box_reward',
                'ordering': ['-drop_rate'],
            },
        ),
        migrations.CreateModel(
            name='MintProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_owner', models.CharField(blank=True, max_length=150, null=True)),
                ('contract_address', models.CharField(max_length=42)),
                ('token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('token_meta_uri', models.CharField(blank=True, max_length=150, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='metadata', null=True)),
                ('strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('endurance', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('lootbox_total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mint_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('REFERRAL_SIGNUP', 'Referral Signup Bonus'), ('REFERRAL_TASK_COMPLETION', 'Referral Task Completion Bonus')], max_length=30)),
                ('quantity_awarded', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points_value', models.IntegerField(help_text='Total points value of the reward', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.fooditem')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'db_table': 'referral_reward',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('SOCIAL_TASK', 'Social Task Completion'), ('REFERRAL_BONUS', 'Referral Bonus'), ('MANUAL_AWARD', 'Manual Award'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('FOOD_CONSUMPTION', 'Food Consumption'), ('REFERRAL_FOOD_REWARD', 'Referral Food Reward'), ('GAME_SCORE', 'Game Score Submission')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.foodconsumption')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.socialtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
                ('referral_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.referralreward')),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'db_table': 'points_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLootBoxPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_purchased', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_opened', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.fooditem')),
                ('loot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.lootbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lootbox_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Loot Box Purchase',
                'verbose_name_plural': 'User Loot Box Purchases',
                'db_table': 'user_loot_box_purchase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLootBoxReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_won', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('current_owner', models.CharField(blank=True, max_length=150, null=True)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('token_id', models.PositiveIntegerField(blank=True, null=True)),
                ('token_meta_uri', models.CharField(blank=True, max_length=150, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='metadata', null=True)),
                ('status', models.CharField(choices=[('user_win', 'User Win'), ('mint_start', 'mint_start'), ('error', 'error'), ('transfer_done', 'Transfer Done')], default='user_win', help_text='status', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loot_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='user.lootbox')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='user.userlootboxpurchase')),
                ('reward_food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='won_from_lootboxes', to='user.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lootbox_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Loot Box Reward',
                'verbose_name_plural': 'User Loot Box Rewards',
                'db_table': 'user_loot_box_reward',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_inventory', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.fooditem')),
            ],
            options={
                'verbose_name': 'Food Inventory',
                'verbose_name_plural': 'Food Inventories',
                'db_table': 'food_inventory',
                'ordering': ['food_item__name'],
                'unique_together': {('user', 'food_item')},
            },
        ),
    ]
