# Generated by Django 5.2.12 on 2026-03-06 09:56

import environment.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userlootboxreward_loot_box_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lootbox',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='lootboxreward',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=environment.storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
