# Generated by Django 5.2.12 on 2026-03-06 11:27

import environment.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_lootbox_image_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootbox',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=environment.storage.PublicMediaStorage(), upload_to=''),
        ),
    ]
