# Generated by Django 5.2.12 on 2026-03-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0004_lootbox_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active_tab_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_active',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lootbox',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mintprofile',
            name='contract_address',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='mintprofile',
            name='token_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, db_index=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='userlootboxreward',
            name='contract_address',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='userlootboxreward',
            name='status',
            field=models.CharField(choices=[('user_win', 'User Win'), ('mint_start', 'mint_start'), ('error', 'error'), ('transfer_done', 'Transfer Done')], db_index=True, default='user_win', max_length=30),
        ),
        migrations.AlterField(
            model_name='userlootboxreward',
            name='token_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='foodconsumption',
            index=models.Index(fields=['user', '-created_at'], name='foodcons_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='foodconsumption',
            index=models.Index(fields=['food_item'], name='foodcons_food_idx'),
        ),
        migrations.AddIndex(
            model_name='foodinventory',
            index=models.Index(fields=['user', 'food_item'], name='foodinv_user_food_idx'),
        ),
        migrations.AddIndex(
            model_name='foodinventory',
            index=models.Index(fields=['user', 'last_updated'], name='foodinv_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['active', 'name'], name='fooditem_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='lootbox',
            index=models.Index(fields=['is_active', '-created_at'], name='lootbox_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lootbox',
            index=models.Index(fields=['cost_food_item'], name='lootbox_cost_food_idx'),
        ),
        migrations.AddIndex(
            model_name='lootboxreward',
            index=models.Index(fields=['loot_box', 'rarity'], name='lootreward_box_rarity_idx'),
        ),
        migrations.AddIndex(
            model_name='lootboxreward',
            index=models.Index(fields=['loot_box', '-drop_rate'], name='lootreward_box_drop_idx'),
        ),
        migrations.AddIndex(
            model_name='mintprofile',
            index=models.Index(fields=['contract_address', 'token_id'], name='mintprofile_contract_token_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['referrer', '-created_at'], name='refreward_referrer_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['referred_user', '-created_at'], name='refreward_referred_idx'),
        ),
        migrations.AddIndex(
            model_name='referralreward',
            index=models.Index(fields=['reward_type'], name='refreward_type_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-total_points', 'date_joined'], name='user_points_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referred_by'], name='user_referred_by_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['wallet_address'], name='user_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxpurchase',
            index=models.Index(fields=['user', 'loot_box'], name='userlootpurchase_user_box_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxpurchase',
            index=models.Index(fields=['user', '-created_at'], name='upurchase_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxreward',
            index=models.Index(fields=['user', '-opened_at'], name='ulootreward_user_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxreward',
            index=models.Index(fields=['loot_box', '-opened_at'], name='ulootreward_box_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxreward',
            index=models.Index(fields=['contract_address', 'token_id'], name='ulootreward_contract_token_idx'),
        ),
        migrations.AddIndex(
            model_name='userlootboxreward',
            index=models.Index(fields=['status'], name='ulootreward_status_idx'),
        ),
    ]
